### ISSUE TITLE
Sync navtab

### ISSUE THREAD

**Issue by GrantHolcombe** [GrantHolcombe/holcomberacing#2]
Copy css transition from work

-note: better idea add sass and use angular material sass variable for the margin-

**Comment by grantbcs** [comment]
Here is the angular material sass variable for transitions as rendered in browser.  Keep in mind migrating to sass is still a better long term fix.

-webkit-transition: margin-left, 0.2s, all 0.4s cubic-bezier(0.25, 0.8, 0.25, 1);
