### ISSUE TITLE
Style update mobile bugs

### ISSUE THREAD

**Issue by GrantHolcombe** [GrantHolcombe/holcomberacing#8]
Mobile is overflowing y. Make text size more responsive.  Trim time and 20xx from date lables.

**Comment by GrantHolcombe** [comment]
Text has been fixed, found out you can use vw on font-size.  Still need to trim labels to prevent scrolling on tiny iphones.

**Comment by grantbcs** [comment]
Not a mobile bug but set a m query for screens over ~1k and lock vw font sizes.
